CREATE TABLE TEST
(
  ID           NUMBER(3, 0)       NOT NULL ENABLE,
  NAME         VARCHAR2(255 CHAR) NOT NULL ENABLE,
  VALUE        VARCHAR2(255 CHAR) NOT NULL ENABLE,
  CONTENT_BLOB BLOB,
  CONTENT_CLOB CLOB,
  CONSTRAINT TEST_PK PRIMARY KEY (ID)
);

CREATE SEQUENCE test_sequence;

CREATE OR REPLACE TRIGGER TEST_ON_INSERT
  BEFORE INSERT
  ON test
  FOR EACH ROW
  BEGIN
    SELECT test_sequence.nextval
    INTO :new.id
    FROM dual;
  END;
/

ALTER TRIGGER TEST_ON_INSERT ENABLE;

INSERT INTO TEST (NAME, VALUE) VALUES ('foo', 'bar');
INSERT INTO TEST (NAME, VALUE) VALUES ('bar', 'baz');

CREATE TABLE TEST_CHARSET
(
  ID     NUMBER(3, 0)       NOT NULL ENABLE,
  FIELD$ VARCHAR2(255 CHAR) NOT NULL ENABLE,
  FIELD_ VARCHAR2(255 CHAR) NOT NULL ENABLE,
  CONSTRAINT TESTCHARSET_PK PRIMARY KEY (ID)
);

CREATE SEQUENCE testcharset_sequence;

CREATE OR REPLACE TRIGGER TESTCHARSET_ON_INSERT
  BEFORE INSERT
  ON TEST_CHARSET
  FOR EACH ROW
  BEGIN
    SELECT testcharset_sequence.nextval
    INTO :new.id
    FROM dual;
  END;
/

ALTER TRIGGER TESTCHARSET_ON_INSERT ENABLE;

INSERT INTO TEST_CHARSET (FIELD$, FIELD_) VALUES ('foo', 'bar');
INSERT INTO TEST_CHARSET (FIELD$, FIELD_) VALUES ('bar', 'baz');

COMMIT;